### ISSUE TITLE
Color format the Fsociety ASCII logo (using colorama)

### ISSUE THREAD

**Issue by LunaticPython2003** [gdscsmit/fsociety#6]
## Tasks to be done
- Colorize the Fsociety logo using colorama (or any other library)
- Randomly keep changing the color scheme 

<b> Note </b> - If any other module is used, its name should be mentioned in the requirements.txt file

**Comment by EncodeNeel** [comment]
@LunaticPython2003 I want to work on this issue.

**Comment by LunaticPython2003** [comment]
Go ahead @Emondrax007

**Comment by swarnabha-dev** [comment]
@LunaticPython2003 I have done the colorizing of Fsociety logo.
